Wip/user logging
LD-Lepricon-DIgitals/del_front pull request #17
Opened 2024-11-29 07:14 UTC by rybmks

2024-11-29 11:57 UTC, Hang-Petrov requested changes
Small adjustments with the comments, text
Also, I don't see the sense of the commented part or the conditions when do we need to delete it

2024-11-29 11:57 UTC, Hang-Petrov commented on src/App.js
>  // Лениво загружаемые компоненты
Maybe translate that to eng/ua (better eng)?
Or delete it

2024-11-29 11:57 UTC, Hang-Petrov commented on src/pages/shared/navigation/RegisterForm/RegisterFormContent.jsx
> +        // Удаление лишних пробелов
Same thing with the language. Translate that to eng/ua (better eng) or delete

2024-11-29 11:57 UTC, Hang-Petrov commented on src/pages/shared/navigation/RegisterForm/RegisterFormContent.jsx
> +        // Формирование данных для API
Same thing with the language

2024-11-29 11:57 UTC, Hang-Petrov commented on src/pages/shared/navigation/RegisterForm/RegisterFormContent.jsx
> +            alert("Сталася помилка. Спробуйте знову пізніше.");
Maybe without the dot?

2024-11-29 11:57 UTC, Hang-Petrov commented on src/pages/shared/navigation/navigation.jsx
> +// Стили
Language

2024-11-29 11:57 UTC, Hang-Petrov commented on src/pages/shared/navigation/navigation.jsx
> +// Хуки
Language

2024-11-29 11:57 UTC, Hang-Petrov commented on src/pages/shared/navigation/navigation.jsx
> +// React и хуки
Language

2024-11-29 11:57 UTC, Hang-Petrov commented on src/pages/shared/navigation/navigation.jsx
> +// Компоненты
Language

2024-11-29 11:57 UTC, Hang-Petrov commented on src/pages/shared/navigation/navigation.jsx
> +// Иконки
Language

2024-11-29 11:57 UTC, Hang-Petrov commented on src/pages/shared/navigation/navigation.jsx
> +// API и контексты
Language

2024-11-29 11:57 UTC, Hang-Petrov commented on src/pages/shared/navigation/navigation.jsx
> +// Роутинг
Language

2024-11-29 11:57 UTC, Hang-Petrov commented on src/pages/shared/navigation/navigation.jsx
> +    // СЛУЖЕБНЫЙ (нужен для вывода юзер даты сразу после того, как она изменилась, потом убрать)
Language - 1
U didn't put an additional info about the time when do we need to delete it
Or I don't see the point of this part there

2024-11-30 11:48 UTC, FUZIR approved these changes

2024-11-30 11:55 UTC, Hang-Petrov approved these changes

2024-11-30 11:55 UTC, merged